using System.Text.Json;
using SmartSearch.Desktop;

var root = Path.GetFullPath(args[0]);
var first = Path.Combine(root, "npm 1 & space");
var second = Path.Combine(root, "npm 2 & space");
var now = DateTimeOffset.UtcNow;
var checks = 0;
var fail = false;
Task<string> Load() { checks++; return fail ? Task.FromException<string>(new IOException("offline")) : Task.FromResult("1.2.4"); }
var manager = new CLIInstallationManager(Path.Combine(root, "state"), first + Path.PathSeparator + second, Load, () => now);
await manager.DiscoverAsync();
Check(manager.Npm?.Prefix == first && manager.Selected is { Compatible: false, CanManage: true }, "Legacy installation detection");
Check(!File.Exists(Path.Combine(root, "legacy-executed")), "Must not run legacy Python wrapper");
manager.SetNpmPath(Path.Combine(root, "missing", "npm.cmd"));
await manager.DiscoverAsync();
Check(manager.Npm is null && manager.Selected is null, "Manual invalid path must not auto-fallback");
manager.SetNpmPath(Path.Combine(second, "npm.cmd"));
await manager.DiscoverAsync();
Check(manager.Npm?.Prefix == second && manager.Selected?.Compatible == true, "Manual path with spaces and ampersand must use trusted npm JS without cmd.exe");
await manager.CheckAutomaticallyAsync(onLaunch: true);
await manager.CheckAutomaticallyAsync(onLaunch: true);
Check(checks == 1 && manager.UpdateAvailable, "Startup/update notification");
now = now.AddSeconds(86399);
await manager.CheckAutomaticallyAsync();
Check(checks == 1, "Early periodic check");
now = now.AddSeconds(1);
await manager.CheckAutomaticallyAsync();
Check(checks == 2, "24 hour check");
var success = manager.CheckedAt;
fail = true;
now = now.AddHours(24);
await manager.CheckAutomaticallyAsync();
await manager.CheckAutomaticallyAsync();
Check(checks == 3 && manager.CheckedAt == success && manager.CheckError.Length > 0, "Failure cache and retry backoff");
manager.SetAutomaticChecks(false);
now = now.AddHours(24);
await manager.CheckAutomaticallyAsync();
Check(checks == 3, "Disabled preference");
fail = false;
await manager.CheckVersionAsync();
await manager.InstallOrRepairAsync("1.2.4");
Check(manager.Selected is { Compatible: true, Version: "1.2.4" }, "Postinstall verification");
var restored = new CLIInstallationManager(Path.Combine(root, "state"), first + Path.PathSeparator + second, Load, () => now);
await restored.DiscoverAsync();
Check(restored.ManualNpmPath == manager.ManualNpmPath && !restored.AutomaticallyChecks && restored.CheckedAt == manager.CheckedAt, "Persisted preferences");
await manager.UninstallAsync();
var arguments = JsonSerializer.Deserialize<string[]>(File.ReadAllText(Path.Combine(second, "operations.json")))!;
Check(arguments.SequenceEqual(["uninstall", "--global", "--prefix", second, "@konbakuyomu/smart-search"]), "Scoped uninstall arguments");
Check(File.Exists(Path.Combine(first, "node_modules", "@konbakuyomu", "smart-search", "package.json")), "Other npm installation changed");
Console.WriteLine("PASS: native Windows npm lifecycle, spaces/ampersand, manual override, legacy isolation, startup/24h checks, failure backoff and persistence");
static void Check(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
